### ISSUE TITLE
control temperature in chatgpt via chatgpt WEB (pandora)

### ISSUE THREAD

**Issue by jaodei** [hibobmaster/matrix_chatgpt_bot#20]
Hi,

I see in v3.py, we are able to change the temperature of chatgpt, which you default to 0.5. Does it also apply when we use chatgpt via chatgpt WEB (pandora)? 

Also is text-davinci-002-render-sha-mobile the only or the best model in pandora_api_model? Any other options?

Thank you.

**Comment by hibobmaster** [comment]
We can't change temperature since it is controlled by ChatGPT Web.
`v3.py` use official chatgpt api endpoint which can specific [temperature](https://platform.openai.com/docs/api-reference/chat/create).  I will delete `v3.py` in [v1.2.0](https://github.com/hibobmaster/matrix_chatgpt_bot/milestone/4) to achieve session isolation(Use node-chatgpt-api instead like bing). 
By default, temperature uses in node-chatgpt-api is [0.8](https://github.com/waylaidwanderer/node-chatgpt-api/blob/74ddbdf85ffbba96025f70d64120c916f170d192/src/ChatGPTClient.js#L52), i can provide an option to change it.

For free account we can use `text-davinci-002-render-sha` and `text-davinci-002-render-sha-mobile` :
```json
{
    "models": [
        {
            "slug": "text-davinci-002-render-sha",
            "max_tokens": 8191,
            "title": "Turbo (Default for free users)",
            "description": "Our fastest model, great for most everyday tasks.",
            "tags": [
                "gpt3.5"
            ],
            "qualitative_properties": {}
        },
        {
            "slug": "text-davinci-002-render-sha-mobile",
            "max_tokens": 8191,
            "title": "Turbo (Default for free users)",
            "description": "Our fastest model, great for most everyday tasks.",
            "tags": [
                "mobile"
            ],
            "qualitative_properties": {}
        }
    ],
    "categories": [
        {
            "category": "gpt_3.5",
            "human_category_name": "GPT-3.5",
            "subscription_level": "free",
            "default_model": "text-davinci-002-render-sha",
            "browsing_model": null,
            "code_interpreter_model": null,
            "plugins_model": null
        }
    ]
}
```

If you have chatgpt plus, you can also get models following the steps below:
1. install pandora from pip
`pip install pandora-chatgpt`
2. launch http service and login
`pandora -s`
3. access `http://127.0.0.1:8008/api/models` to find which models you can use

**Comment by jaodei** [comment]
Well explained. Thank you!
